---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  #- name: ubuntu-12.04
  #- name: centos-6.5
  #  driver:
  #    vagrantfile_erb: Vagrantfile.erb
  - name: centos-7.0
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']

busser:
  sudo: false

suites:
  - name: default
    run_list:
      #- recipe[ubuntu-change-source-list]
      #- recipe[apt]
      - recipe[timezone-ii]
      - recipe[yum]
      - recipe[java]
      - recipe[build-essential]
      - recipe[r-compiledfromsource@0.2.0]
      - recipe[r31biocdev::default]
    attributes:
      ubuntu:
        mirror_site_url: http://ftp.jaist.ac.jp/pub/Linux/ubuntu/
        version: 12.04
        need_deb_src: false
        need_update: true
      tz: "Asia/Tokyo"
      r_compiledfromsource:
        sourceurl: "ftp://ftp.stat.math.ethz.ch/Software/R/R-devel.tar.gz"
      r31biocdev:
        r_prefix_path: "/usr/local/R-devel/bin/"
      java:
        install_flavor: "oracle"
        jdk_version: 8
        oracle:
          accept_oracle_download_terms: true
