---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  #- name: ubuntu-12.04
  #- name: centos-6.5
  #  driver:
  #    vagrantfile_erb: Vagrantfile.erb
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[r-compiledfromsource::change-apt]
      - recipe[timezone_lwrp]
      #- recipe[ubuntu-change-source-list]
      #- recipe[apt]
    attributes:
      java:
        install_flavor: "openjdk"
        jdk_version: 7
      apt:
        compile_time_update: true
      build-essential:
        compile_time: true
      ubuntu:
        mirror_site_url: "http://ftp.jaist.ac.jp/pub/Linux/ubuntu/"
        version: "14.04"
        need_deb_src: false
        need_update: true
  - name: centos-7
    driver:
      box: bento/centos-7.2
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[yum]
    attributes:
      yum:
        main:
          keepcache:  True
      java:
        install_flavor: "openjdk"
        jdk_version: 7

busser:
  sudo: false

suites:
  - name: default
    run_list:
      #- recipe[ubuntu-change-source-list]
      #- recipe[apt]
      - recipe[timezone_lwrp]
      - recipe[java]
      - recipe[build-essential]
      - recipe[r-compiledfromsource]
      - recipe[r31biocdev::default]
    attributes:
      tz: "Asia/Tokyo"
      r_compiledfromsource:
        sourceurl: "http://stat.ethz.ch/R/daily/R-devel.tar.gz"
      r31biocdev:
        r_prefix_path: "/usr/local/R-devel/bin/"
